version: '3.8'

# Example Docker Compose configuration using environment variables
# This demonstrates how to run the mass ingestion container with runtime credentials

services:
  moderne-ingestion:
    image: moderne-mass-ingest:latest
    
    # Load environment variables from .env file
    env_file:
      - .env
    
    # Or specify individual environment variables
    environment:
      # Git credentials (multiline string)
      - |
        GIT_CREDENTIALS=
        https://user:token@github.com
        https://user:token@gitlab.com
      
      # SSH configuration
      - SSH_PRIVATE_KEY=${SSH_PRIVATE_KEY}
      - SSH_KNOWN_HOSTS=${SSH_KNOWN_HOSTS}
      - SSH_STRICT_HOST_KEY_CHECKING=${SSH_STRICT_HOST_KEY_CHECKING:-true}
      
      # Git SSL verification
      - GIT_SSL_VERIFY=${GIT_SSL_VERIFY:-true}
      
      # Maven configuration
      - MAVEN_SETTINGS_XML=${MAVEN_SETTINGS_XML}
      - MAVEN_SETTINGS_SECURITY_XML=${MAVEN_SETTINGS_SECURITY_XML}
      
      # Gradle configuration
      - GRADLE_PROPERTIES=${GRADLE_PROPERTIES}
      
      # Custom CA certificate
      - CUSTOM_CA_CERT=${CUSTOM_CA_CERT}
      - CONFIGURE_WGET_CA=${CONFIGURE_WGET_CA:-false}
      
      # NPM configuration
      - NPM_REGISTRY=${NPM_REGISTRY:-https://registry.npmjs.org/}
      - NPM_AUTH_TOKEN=${NPM_AUTH_TOKEN}
      
      # Python configuration
      - PIP_INDEX_URL=${PIP_INDEX_URL}
      - PIP_TRUSTED_HOST=${PIP_TRUSTED_HOST}
      
      # Runtime override of artifact repository (if not set at build time)
      - PUBLISH_URL=${PUBLISH_URL}
      - PUBLISH_USER=${PUBLISH_USER}
      - PUBLISH_PASSWORD=${PUBLISH_PASSWORD}
      - PUBLISH_TOKEN=${PUBLISH_TOKEN}
      
      # Moderne platform credentials
      - MODERNE_TENANT=${MODERNE_TENANT}
      - MODERNE_TOKEN=${MODERNE_TOKEN}
    
    ports:
      - "8080:8080"  # Metrics
      - "3000:3000"  # Grafana
      - "9090:9090"  # Prometheus
    
    volumes:
      # Mount data directory for cloned repositories
      - ./data:/var/moderne
      
      # Mount repos.csv
      - ./repos.csv:/app/repos.csv:ro
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 32G
          cpus: '4'
        reservations:
          memory: 16G
          cpus: '2'