{
 "title": "Moderne CLI - Runs",
 "description": "Monitors the performance of recipe runs.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Recipe run stages",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(moderne_cli_run_stages_seconds_sum) by (stage)/sum(moderne_cli_run_stages_seconds_count) by (stage)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max run duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(moderne_cli_run_seconds_max)",
     "legendFormat": "longest run"
    }
   ]
  },
  {
   "title": "Run duration distribution",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(moderne_cli_run_seconds_bucket[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Run throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(rate(moderne_cli_run_seconds_count[1m]) * 60)",
     "legendFormat": "throughput"
    }
   ]
  },
  {
   "title": "Run success rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(moderne_cli_run_seconds_count{outcome=\"success\"}[30m]))/sum(sum_over_time(moderne_cli_run_seconds_count[30m]))",
     "legendFormat": "30 minute moving success rate"
    }
   ]
  },
  {
   "title": "Dependency resolution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Max time to download Maven POM",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 10, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(rewrite_maven_download_seconds_max{type=\"pom\",command=\"run\"}) by (outcome)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Max time to download Maven POM",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 10, "x": 10, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(rewrite_maven_download_seconds_sum{type=\"pom\",command=\"run\"}) by (outcome)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "JVM GC Overhead",
   "type": "timeseries",
   "description": "Time spent in GC as a percentage of total wall clock time.",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(jvm_gc_overhead_percent{command=\"run\"}) by (process)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC Pauses",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_pause_seconds_count{command=\"run\"}[1m])) by (process)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "description": "The top consuming heap spaces by process and space.",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(process_cpu_usage{command=\"run\"}) by (process)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top JVM Heap Utilization",
   "type": "timeseries",
   "description": "The top consuming heap spaces by process and space.",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(5, sum(jvm_memory_used_bytes{command=\"run\"}) by (process,id))",
     "legendFormat": "{{process}} - {{id}}"
    }
   ]
  },
  {
   "title": "JVM Committed Memory",
   "type": "timeseries",
   "description": "The amount of memory in bytes that is committed for the Java virtual machine to use. This amount of memory is guaranteed for the Java virtual machine to use.",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(5, sum(jvm_memory_committed_bytes{command=\"run\"}) by (process))",
     "legendFormat": "{{process}}"
    }
   ]
  },
  {
   "title": "JVM Max Memory",
   "type": "timeseries",
   "description": "The maximum amount of memory in bytes that can be used for memory management (e.g. -Xmx value).",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(5, sum(jvm_memory_max_bytes{command=\"run\"}) by (process))",
     "legendFormat": "{{process}}"
    }
   ]
  }
 ]
}