{
 "title": "Moderne CLI - Builds",
 "description": "Monitors the performance of LST production.",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Max build duration by build tool",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(moderne_cli_build_seconds_max) by (build_tool)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Build duration distribution",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(moderne_cli_build_seconds_bucket[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Build throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(rate(moderne_cli_build_seconds_count[1m]) * 60) by (build_tool)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Build success rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(moderne_cli_build_seconds_count{outcome=\"success\"}[30m]))/sum(sum_over_time(moderne_cli_build_seconds_count[30m]))",
     "legendFormat": "30 minute moving success rate"
    }
   ]
  },
  { "title": "Dependency resolution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Max time to download Maven POM",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(rewrite_maven_download_seconds_max{type=\"pom\",command=\"build\"}) by (outcome)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max time to download Maven POM",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(rewrite_maven_download_seconds_sum{type=\"pom\",command=\"build\"}) by (outcome)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "JVM GC Overhead",
   "type": "timeseries",
   "description": "Time spent in GC as a percentage of total wall clock time.",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(jvm_gc_overhead_percent{command=\"build\"}) by (process)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC Pauses",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_pause_seconds_count{command=\"build\"}[1m])) by (process)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "description": "The top consuming heap spaces by process and space.",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(process_cpu_usage{command=\"build\"}) by (process)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top JVM Heap Utilization",
   "type": "timeseries",
   "description": "The top consuming heap spaces by process and space.",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(5, sum(jvm_memory_used_bytes{command=\"build\"}) by (process,id))",
     "legendFormat": "{{process}} - {{id}}"
    }
   ]
  }
 ]
}